export default function Main() {
  return (
    <main>
      <figure>
        <img
          src="https://lumiere-a.akamaihd.net/v1/images/encanto_ka_bpo_pay1_ee2c2e0c.jpeg"
          alt=""
        />
      </figure>
      <figure>
        <img
          src="https://lumiere-a.akamaihd.net/v1/images/poster_cf6525c0.png"
          alt=""
        />
      </figure>
      <figure>
        <img
          src="https://lumiere-a.akamaihd.net/v1/images/beta_epic_payoff_brazil_2a5f625f.jpeg"
          alt=""
        />
      </figure>
      <figure>
        <img
          src="https://lumiere-a.akamaihd.net/v1/images/image_425574a7.jpeg?region=0,0,540,810"
          alt=""
        />
      </figure>
      <figure>
        <img
          src="https://artgeist.com.br/wp-content/uploads/2018/05/irmao-urso.jpg"
          alt=""
        />
      </figure>
      <figure>
        <img
          src="https://apostiladecinema.com.br/wp-content/uploads/2021/06/luca-filme-pixar-animacao-disney-2021-critica-poster-scaled-e1629396654805.jpg"
          alt=""
        />
      </figure>
    </main>
  );
}
